/**
 * Generates TypeScript types from the versioned contract schema
 * `dashboard/contracts/dashboard-contracts-v1.schema.json` (read-only).
 *
 * The frontend must never hand-maintain a private copy of the wire model:
 * `npm run codegen` regenerates `src/generated/contracts.types.ts` from the
 * schema, and `npm run codegen:check` fails when the committed output drifts
 * from the schema.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const frontendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.resolve(frontendRoot, "../contracts/dashboard-contracts-v1.schema.json");
const typesOutPath = path.join(frontendRoot, "src/generated/contracts.types.ts");
const validatorsOutPath = path.join(frontendRoot, "src/generated/contracts.validators.ts");

const ROOT_TYPES = ["DashboardSnapshot", "TaskDetail", "Health", "ErrorEnvelope", "SnapshotEvent", "ProjectConsole"];
const SCHEMA_ID = "ai-dev-flow/dashboard-contracts/v1";

const BANNER = `/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-types.mjs from
 * dashboard/contracts/dashboard-contracts-v1.schema.json (ai-dev-flow/dashboard-contracts/v1).
 * Regenerate with: npm run codegen
 */
`;

const VALIDATORS_BANNER = `/* eslint-disable */
// @ts-nocheck
/**
 * GENERATED FILE — DO NOT EDIT.
 * Ajv standalone validators generated at build time from
 * dashboard/contracts/dashboard-contracts-v1.schema.json.
 * No runtime schema compilation or unsafe-eval is required.
 * Regenerate with: npm run codegen
 */
`;

async function assertCurrent(pathname, expected, label) {
  let current;
  try {
    current = await readFile(pathname, "utf-8");
  } catch {
    current = "";
  }
  if (current !== expected) {
    console.error(`${label} is out of date; run npm run codegen`);
    process.exitCode = 1;
    return false;
  }
  return true;
}

function browserEsmStandaloneCode(ajv, refs) {
  const imports = [];
  const code = standaloneCode(ajv, refs).replace(
    /const (func[0-9]+) = require\("([^"]+)"\)\.default;/g,
    (_match, name, modulePath) => {
      const specifier = modulePath.endsWith(".js") ? modulePath : `${modulePath}.js`;
      imports.push(`import ${name} from "${specifier}";`);
      return "";
    },
  );
  if (code.includes("require(")) {
    throw new Error("standalone validator contains an unsupported CommonJS runtime import");
  }
  return `${imports.join("\n")}\n${code}`;
}

async function main() {
  const check = process.argv.includes("--check");
  const raw = await readFile(schemaPath, "utf-8");
  const schema = JSON.parse(raw);

  const seen = new Set();
  let typesOutput = BANNER;
  for (const name of ROOT_TYPES) {
    if (!schema.$defs || !schema.$defs[name]) {
      throw new Error(`schema is missing $defs.${name}; the wire contract changed`);
    }
    // Root-level `$ref` is not resolved by the compiler, so spread the target
    // def and keep `$defs` alongside for its internal references. Shared
    // helper types (e.g. NullableString) are emitted once per name.
    const wrapper = Object.assign({}, schema.$defs[name], { $defs: schema.$defs });
    const ts = await compile(wrapper, name, {
      bannerComment: "",
      declareExternallyReferenced: true,
      strictIndexSignatures: true,
      unknownAny: false,
      format: false,
    });
    for (const block of ts.split(/\n(?=export )/)) {
      const match = /^export (?:type|interface) (\w+)/.exec(block.trim());
      if (!match) {
        continue;
      }
      if (seen.has(match[1])) {
        continue;
      }
      seen.add(match[1]);
      typesOutput += `\n${block.trim()}\n`;
    }
  }

  const ajv = new Ajv2020({
    allErrors: true,
    strict: true,
    code: { source: true, esm: true },
  });
  ajv.addSchema(schema, SCHEMA_ID);
  const validatorRefs = Object.fromEntries(
    ROOT_TYPES.map((name) => [`validate${name}`, `${SCHEMA_ID}#/$defs/${name}`]),
  );
  const validatorsOutput =
    `${VALIDATORS_BANNER}${browserEsmStandaloneCode(ajv, validatorRefs)}\n`;

  if (check) {
    const results = await Promise.all([
      assertCurrent(
        typesOutPath,
        typesOutput,
        "src/generated/contracts.types.ts",
      ),
      assertCurrent(
        validatorsOutPath,
        validatorsOutput,
        "src/generated/contracts.validators.ts",
      ),
    ]);
    if (results.includes(false)) {
      process.exit(1);
    }
    console.log("generated types and validators are in sync with the contract schema");
    return;
  }
  await Promise.all([
    writeFile(typesOutPath, typesOutput),
    writeFile(validatorsOutPath, validatorsOutput),
  ]);
  console.log(`wrote ${path.relative(frontendRoot, typesOutPath)}`);
  console.log(`wrote ${path.relative(frontendRoot, validatorsOutPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
