/**
 * Generates TypeScript types from the versioned contract schema
 * `dashboard/contracts/dashboard-contracts-v1.schema.json` (read-only).
 *
 * The frontend must never hand-maintain a private copy of the wire model:
 * `npm run codegen` regenerates `src/generated/contracts.types.ts` from the
 * schema, and `npm run codegen:check` fails when the committed output drifts
 * from the schema.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const frontendRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.resolve(frontendRoot, "../contracts/dashboard-contracts-v1.schema.json");
const outPath = path.join(frontendRoot, "src/generated/contracts.types.ts");

const ROOT_TYPES = ["DashboardSnapshot", "TaskDetail", "Health", "ErrorEnvelope", "SnapshotEvent"];

const BANNER = `/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-types.mjs from
 * dashboard/contracts/dashboard-contracts-v1.schema.json (ai-dev-flow/dashboard-contracts/v1).
 * Regenerate with: npm run codegen
 */
`;

async function main() {
  const check = process.argv.includes("--check");
  const raw = await readFile(schemaPath, "utf-8");
  const schema = JSON.parse(raw);

  const seen = new Set();
  let output = BANNER;
  for (const name of ROOT_TYPES) {
    if (!schema.$defs || !schema.$defs[name]) {
      throw new Error(`schema is missing $defs.${name}; the wire contract changed`);
    }
    // Root-level `$ref` is not resolved by the compiler, so spread the target
    // def and keep `$defs` alongside for its internal references. Shared
    // helper types (e.g. NullableString) are emitted once per name.
    const wrapper = Object.assign({}, schema.$defs[name], { $defs: schema.$defs });
    const ts = await compile(wrapper, name, {
      bannerComment: "",
      declareExternallyReferenced: true,
      strictIndexSignatures: true,
      unknownAny: false,
      format: false,
    });
    for (const block of ts.split(/\n(?=export )/)) {
      const match = /^export (?:type|interface) (\w+)/.exec(block.trim());
      if (!match) {
        continue;
      }
      if (seen.has(match[1])) {
        continue;
      }
      seen.add(match[1]);
      output += `\n${block.trim()}\n`;
    }
  }

  if (check) {
    let current = "";
    try {
      current = await readFile(outPath, "utf-8");
    } catch {
      current = "";
    }
    if (current !== output) {
      console.error("src/generated/contracts.types.ts is out of date; run npm run codegen");
      process.exit(1);
    }
    console.log("generated types are in sync with the contract schema");
    return;
  }
  await writeFile(outPath, output);
  console.log(`wrote ${path.relative(frontendRoot, outPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
